### ISSUE TITLE
Change Your package.json

### ISSUE THREAD

**Issue by Botiso-Devs** [ModdingTwins/PocketIsland#1]
{
  "name": "Botiso",
  "description": "Heroku Bot",
  "version": "1.0.0",
  "main": "bot.js",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
    "discord.js": "11.4.2",
    "request": "2.81.0",
    "fs": "0.0.2",
    "ms": "2.1.1",
    "discord-eco": "0.0.10"
  }
}

**Comment by ModdingTwins** [comment]
Thanks
